/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactMessage {
  'name' : string,
  'timestamp' : bigint,
  'phone' : string,
  'contactMessage' : string,
}
export interface RFQ {
  'contactPerson' : string,
  'productType' : string,
  'email' : string,
  'grade' : string,
  'deliveryTimeline' : string,
  'timestamp' : bigint,
  'companyName' : string,
  'quantityUnit' : string,
  'quantity' : bigint,
  'requests' : bigint,
  'phone' : string,
  'specialRequirements' : [] | [string],
  'material' : string,
}
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'getAllContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getAllRFQs' : ActorMethod<[], Array<RFQ>>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'submitRFQ' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      [] | [string],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];