/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactMessage = IDL.Record({
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'contactMessage' : IDL.Text,
});
export const RFQ = IDL.Record({
  'contactPerson' : IDL.Text,
  'productType' : IDL.Text,
  'email' : IDL.Text,
  'grade' : IDL.Text,
  'deliveryTimeline' : IDL.Text,
  'timestamp' : IDL.Int,
  'companyName' : IDL.Text,
  'quantityUnit' : IDL.Text,
  'quantity' : IDL.Nat,
  'requests' : IDL.Nat,
  'phone' : IDL.Text,
  'specialRequirements' : IDL.Opt(IDL.Text),
  'material' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'getAllRFQs' : IDL.Func([], [IDL.Vec(RFQ)], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'submitRFQ' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactMessage = IDL.Record({
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'contactMessage' : IDL.Text,
  });
  const RFQ = IDL.Record({
    'contactPerson' : IDL.Text,
    'productType' : IDL.Text,
    'email' : IDL.Text,
    'grade' : IDL.Text,
    'deliveryTimeline' : IDL.Text,
    'timestamp' : IDL.Int,
    'companyName' : IDL.Text,
    'quantityUnit' : IDL.Text,
    'quantity' : IDL.Nat,
    'requests' : IDL.Nat,
    'phone' : IDL.Text,
    'specialRequirements' : IDL.Opt(IDL.Text),
    'material' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'getAllContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'getAllRFQs' : IDL.Func([], [IDL.Vec(RFQ)], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'submitRFQ' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };